version: '3'
services:
  web:
    build:
      context: ./docker/web
    ports:
      - "${WEB_PORT:-3000}:80"
    volumes:
      - ..:/var/www/html

  db:
    image: mariadb:10.3.31
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/db_init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
