CREATE DATABASE project;
CREATE DATABASE test_project;

GRANT ALL PRIVILEGES ON project.* TO user@"%" IDENTIFIED BY 'pass' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON test_project.* TO user@"%" IDENTIFIED BY 'pass' WITH GRANT OPTION;
